name: RedLightGreenLight
version: '${project.version}'
main: nl.jessicavdz.redlightgreenlight.RedLightGreenLight
api-version: '1.20'
commands:

  suicide:
    description: kill yourself
    usage: /<command>

  rules:
    description: Simple rules to make the game a little more fun
    usage: /<command>

  godmode:
    description: An mode only for Op's
    usage: /<command>

  sb:
    description: an scoreboard
    usage: /<command>

  startgame:
    description: an easyway to start the game
    usage: /<command>

  countdown:
    description: start the game
    usage: /<command>

  menu:
    description: menu
    usage: /<command>